export * from '../../shared/constants'

export const LABEL = {
  ABOVE: 'Above',
  ALIGN_TO: 'Align to',
  ALIGNMENT: 'Alignment',
  BACKGROUND_COLOR: 'Background Color',
  BELOW: 'Below',
  BOTH_IMAGES: 'Both Images',
  BOTTOM: 'Bottom',
  CENTER: 'Center',
  CLEAR_BOTH: 'Clear Both',
  CONTAIN: 'Contain',
  COVER: 'Cover',
  DELETE: 'Delete',
  DELETE_ORIGINAL: 'Delete Original',
  DOWNSCALE: 'Downscale Larger Image',
  FLATTEN: 'Flatten',
  FLIP: 'Flip',
  FLOP: 'Flop',
  IMAGE: 'Image',
  INSERT: 'Insert',
  JPEG: 'JPEG',
  KEEP: 'Keep',
  KEEP_BOTH: 'Keep Both',
  LANDSCAPE: 'Landscape',
  LEFT: 'Left',
  LINK_CROP_SLIDERS: 'Link Crop Sliders',
  LOAD_RESULT: 'Load Result',
  NEW_FILE: 'New File',
  ORIGINAL: 'Original',
  PNG: 'PNG',
  PORTRAIT: 'Portrait',
  POST_SAVE_ACTION: 'Post Save Action',
  RELOAD: 'Reload',
  REPLACE: 'Replace',
  REPLACE_ORIGINAL: 'Replace Original',
  REMOVE: 'Remove',
  RIGHT: 'Right',
  ROTATE: 'Rotate',
  SAVE_ACTIONS: "Save Actions",
  SAVE_FORMAT: "Save Format",
  SAVE_IMAGE: 'Save Image',
  SAVE_ON_DROP: 'Save on Drop',
  SIZING: "Sizing",
  SWAP_IMAGES: 'Swap Images',
  SWITCH_TO: 'Switch to',
  TIFF: 'TIFF',
  TOP: 'Top',
  UNLINK_CROP_SLIDERS: 'Unlink Crop Sliders',
  UPLOAD: 'Upload',
  UPSCALE: 'Upscale Smaller Image',
  WARN: 'Warn',
  WEBP: 'WEBP'
} as const

export const LABEL_LR_VALUES = [ LABEL.LEFT, LABEL.RIGHT ] as const
export const LABEL_TB_VALUES = [ LABEL.TOP, LABEL.BOTTOM ] as const
